name: "GreetContributor"
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  GreetCommitter:
    runs-on: ubuntu-latest
    steps:
      - name: "Greet contributor"
        uses: ibakshay/greet-contributors-action@test-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          content: "Thank you for creating this pull request and contributing to TinDog! 😊 The maintainers will review this Pull Request and provide feedback as soon as possible! 😇"
